"""empty message

Revision ID: 6b6e8b2910ac
Revises: 2c224df9a041
Create Date: 2025-05-02 14:56:00.676283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6e8b2910ac'
down_revision: Union[str, None] = '2c224df9a041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_delivery_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('delivery_method', sa.Enum('EMAIL', 'TELEGRAM', 'PLATFORM', name='deliverymethodenum', native_enum=False), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'FAILED', 'SENDING', name='deliverystatusenum', native_enum=False), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['generated_reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'activation_keys', ['key'])
    op.add_column('generated_reports', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'generated_reports', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'generated_reports', type_='foreignkey')
    op.drop_column('generated_reports', 'user_id')
    op.drop_constraint(None, 'activation_keys', type_='unique')
    op.drop_table('report_delivery_log')
    # ### end Alembic commands ###
