"""empty message

Revision ID: b3e6d06d5b6e
Revises: 1d1e6cfa26c9
Create Date: 2025-04-29 17:05:54.915662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e6d06d5b6e'
down_revision: Union[str, None] = '1d1e6cfa26c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_name', sa.String(length=255), nullable=True),
    sa.Column('report_url', sa.String(length=512), nullable=True),
    sa.Column('excel_url', sa.String(length=512), nullable=True),
    sa.Column('template_url', sa.String(length=512), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_at', 'generated_reports', ['generated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_generated_at', table_name='generated_reports')
    op.drop_table('generated_reports')
    # ### end Alembic commands ###
